-- environment.lua
hypr.set_env("HYRCURSOR_THEME", "Bibata-Modern-Ice")
hypr.set_env("HYPRCURSOR_SIZE", "24")
hypr.set_env("CLUTTER_BACKEND", "wayland")
hypr.set_env("GDK_BACKEND", "wayland,x11")
hypr.set_env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hypr.set_env("QT_QPA_PLATFORM", "wayland;xcb")
hypr.set_env("QT_QPA_PLATFORMTHEME", "qt6ct")
hypr.set_env("QT_SCALE_FACTOR", "1")
hypr.set_env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hypr.set_env("XDG_CURRENT_DESKTOP", "Hyprland")
hypr.set_env("XDG_SESSION_DESKTOP", "Hyprland")
hypr.set_env("XDG_SESSION_TYPE", "wayland")
hypr.set_env("GRIMBLAST_HIDE_CURSOR", "0")
hypr.set_env("MOZ_ENABLE_WAYLAND", "1")
hypr.set_env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
-- Uncomment for NVIDIA:
-- hypr.set_env("LIBVA_DRIVER_NAME", "nvidia")
-- hypr.set_env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
-- hypr.set_env("GBM_BACKEND", "nvidia-drm")
